[debug] [2022-10-21T22:55:41.400Z] ----------------------------------------------------------------------
[debug] [2022-10-21T22:55:41.402Z] Command:       /usr/bin/node /usr/bin/firebase deploy
[debug] [2022-10-21T22:55:41.402Z] CLI Version:   11.15.0
[debug] [2022-10-21T22:55:41.403Z] Platform:      linux
[debug] [2022-10-21T22:55:41.403Z] Node Version:  v18.11.0
[debug] [2022-10-21T22:55:41.403Z] Time:          Fri Oct 21 2022 17:55:41 GMT-0500 (Central Daylight Time)
[debug] [2022-10-21T22:55:41.403Z] ----------------------------------------------------------------------
[debug] 
[debug] [2022-10-21T22:55:41.492Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/undefined [none]
[debug] [2022-10-21T22:55:41.759Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/undefined 403
[debug] [2022-10-21T22:55:41.760Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/undefined {"error":{"code":403,"message":"The caller does not have permission","status":"PERMISSION_DENIED"}}
[debug] [2022-10-21T22:55:41.761Z] HTTP Error: 403, The caller does not have permission
[debug] [2022-10-21T22:55:41.869Z] FirebaseError: HTTP Error: 403, The caller does not have permission
    at responseToError (/usr/lib/node_modules/firebase-tools/lib/responseToError.js:49:12)
    at RetryOperation._fn (/usr/lib/node_modules/firebase-tools/lib/apiv2.js:288:77)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[error] 
[error] Error: Failed to get Firebase project undefined. Please make sure the project exists and your account has permission to access it.
